### ISSUE TITLE
Make test accounts optional

### ISSUE THREAD

**Issue by aliusmiles** [ConsenSys/quorum-genesis-tool#28]
Generated genesis.json always include hardcoded test accounts, would be better to make them optional so they can be skipped for example in genesis.json generated for [quorum-kubernetes](https://github.com/ConsenSys/quorum-kubernetes/issues/137)

**Comment by Ezzahhh** [comment]
Added a CLI flag `quickstartDevAccounts` and an additional question whether quorum-dev-quickstart test accounts should be added.
