### ISSUE TITLE
some questions default values do not work as expected

### ISSUE THREAD

**Issue by aliusmiles** [ConsenSys/quorum-genesis-tool#30]
`Choose number of member node keys to generate: (integer) Default: 2` default seems to be set at 1. 

`Include quorum-dev-quickstart test accounts: [y/N]` default 'N' doesn't work, shows an error:

```
Sorry, but I didn't understand your answer. Please select Y or N,
or just hit enter if you want the default.
```

Steps to reproduce: `npx quorum-genesis-tool` and just press Enter to use default configs.

**Comment by Ezzahhh** [comment]
Hello, 

Thank you for reporting this. There has been a release addressing these in [0.1.8](https://github.com/ConsenSys/quorum-genesis-tool/releases/tag/0.1.8). I will close the issue now unless you run into any similar issues.
