### ISSUE TITLE
Missing quotes in besu config template

### ISSUE THREAD

**Issue by tarasbsbr** [ConsenSys/quorum-genesis-tool#32]
Missing closing quotes mark after `“DEBUG` :

https://github.com/ConsenSys/quorum-genesis-tool/blob/ed440b2f65132b303d3a1084432f9cc84d941abb/src/templates/besuConfigTemplate.toml#L23

https://github.com/ConsenSys/quorum-genesis-tool/blob/ed440b2f65132b303d3a1084432f9cc84d941abb/src/templates/besuConfigTemplate.toml#L30

**Comment by Ezzahhh** [comment]
Release 0.1.9 should address this and available on npm/npx. Thank you for reporting
