### ISSUE TITLE
Bug while running npx quorum-genesis-tool, no such file or directory[build/templates/README.md]

### ISSUE THREAD

**Issue by deepakshrma** [ConsenSys/quorum-genesis-tool#37]
Seems while publishing build/templates golder is not coied. I copy templates folder manual from source, It is working.

*Details:*

- Command: `npx quorum-genesis-tool --consensus qbft --chainID 1337 --blockperiod 5 --requestTimeout 10 --epochLength 30000 --difficulty 1 --gasLimit '0xFFFFFF' --coinbase '0x0000000000000000000000000000000000000000' --validators 5 --members 0 --bootnodes 0 --outputPath 'artifacts'`
- NodeJS Details:
```
{
  'codefi-orchestrate-quick-start': '4.0.0',
  npm: '8.15.0',
  node: '16.17.0',
  v8: '9.4.146.26-node.22',
  uv: '1.43.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.47.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q+quic',
  cldr: '41.0',
  icu: '71.1',
  tz: '2022a',
  unicode: '14.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}
```
- Error:  `ENOENT: no such file or directory, open '~/.npm-global/lib/node_modules/quorum-genesis-tool/build/templates/README.md'`

**Comment by Ezzahhh** [comment]
Thanks for reporting this, the version 0.2.3 was pushed out with this issue fixed
