### ISSUE TITLE
Enhancement: specify milestone, add pre funded accounts or contracts

### ISSUE THREAD

**Issue by soragXYZ** [ConsenSys/quorum-genesis-tool#40]
Hi!

Is it possible to add more options to QGT ?

I'm asking the question because the quorum kubernetes repo is using QGT to generate the genesis file, validators keys, etc... (https://github.com/ConsenSys/quorum-kubernetes/blob/master/helm/charts/besu-genesis/templates/genesis-job-init.yaml#L110), and I'm using this repo to deploy a private Besu network

But I'm lacking some options, like the ability to specify a milestone, or to add pre funded accounts / contracts.

I think that it can be a good idea to have more granularity with the CLI

**Comment by joshuafernandes** [comment]
Hello @soragXYZ 
I've added the milestone blocks to v 0.2.6 and you can use that. Bear in mind GoQuorum doesn't have the EIPs beyond the istanbul block so specifying the block number in genesis may not give the desired effect. 

I've added the other functionality to our backlog and we will work on when we get the chance based on priorities. I'll ping you when it's done. Id encourage you to submit a PR if this is functionality you require and we can review

I'll push a container to the k8s repo with this version. In the interim though I'd suggest running the genesis chart, updating the genesis config map to suit your reqs and then continuing with the rest of the nodes

Cheers
