### ISSUE TITLE
 requesttimeoutseconds is not written in the GoQuorum genesis file.

### ISSUE THREAD

**Issue by ivis-minoue** [ConsenSys/quorum-genesis-tool#43]
When I run the following command, the requesttimeoutseconds is not written in the GoQuorum genesis file.
npx quorum-genesis-tool --consensus qbft --chainID 400 --blockperiod 5 --requestTimeout 10 --validators 4 --members 1 --bootnodes 0
Only Besu genesis file is written requesttimeoutseconds.
Please make sure that requesttimeoutseconds is also written to the GoQuorum genesis file.

**Comment by Ezzahhh** [comment]
Thank you for reporting the issue, it has now been released as part of 0.2.8
