### ISSUE TITLE
feat: add `contractSizeLimit` config to besu genesis file

### ISSUE THREAD

**Issue by 0xDones** [Consensys/quorum-genesis-tool#53]
### Description

Even when the option `maxCodeSize` is provided the field `config.contractSizeLimit` is not created for besu genesis. I think it would be just a matter of adding the code below to the `createBesuGenesis` function on the file `src/lib/genesisGenerate.ts`

```ts
  besu.config.contractSizeLimit = quorumConfig.maxCodeSize;
```

According to the docs, this is a field I should set for running besu on K8s: https://besu.hyperledger.org/private-networks/how-to/configure/free-gas#2-set-the-contract-size

**Comment by joshuafernandes** [comment]
fixed in v 0.2.17
