### ISSUE TITLE
Can we use this tool for production?

### ISSUE THREAD

**Issue by conanoc** [Consensys/quorum-genesis-tool#56]
> Choose number of validator node keys to generate: (integer) Default: 4

This tool generates validator node keys instead of accepting node keys from inputs. Is this a safe procedure for production?
I wonder if each of the four validators should generate their own keys.

**Comment by joshuafernandes** [comment]
Yes, this can be used for production.

Depending on who is maintaining the network nodes in the consortium you can:
1. Have some precreated via the tool and then once everything is working, vote the new ones in and vote the old ones out.
2. Start with keys from the validators and hand assemble the genesis - you can still do that here by modyfying the extra data field in the genesis. Alternatively start the network with just your user (set validator as 1) and then add the other validators in by voting them in

Cheers
